### PR TITLE
MSFT_xFileSystemAccessRule: Fixing enum flag handling and adding better tests, #20

### LINKED ISSUE #20: xFileSystemAccessRule: Test configuration always retrieves "False"
Start-Dsc... works fine but when I run Test, I get False.

Here's my configuration:

```
                xFileSystemAccessRule ReadControlRedirectionDirectoryEnsure
                {
                    Ensure      = "Present"
                    Path        = "C:\inetpub\wwwroot\wss\VirtualDirectories\redirect"
                    Identity    = "IIS_IUSRS"
                    Rights      = @("ReadAndExecute")
                    DependsOn   = "[File]RedirectionDirectoryEnsure"
                }
```

### PR DESCRIPTION
**Pull request by EklipZgit**
This resource had three major bugs that I sussed out while investigating and fixing #20 , which are all covered now in the additional functional tests that I added.

1: The resource 'test' function string-compared existing rights as a single string against an array of input Rights, which was the cause of the #20 (almost)-always-fails-the-test bug. 
Repro was:
Set "Read" on a folder. The next 'Test' would retrieve the value 'Read, Synchronize', as synchronize is automatically added with Read by the OS.
@('Read') was then compare-object'd against @('Read, Synchronize') *NOTE SINGLE STRING*, causing the obvious test failure, causing Set to re-run on every DSC run.
However the fix wasn't as easy as switching the compare object to @('Read, Synchronize') -split ', ' due to the fact that the Enum is flag based which leads us to (2) below. 

2: The script didn't properly take into account the subset-ness of the Flagged enum. 
For example, manually set permissions on a folder granting something FullControl, and then create a mof assigning "Read" to that same folder. The test fails, but the 'Set' does not correct the issue because applying Read to something with FullControl does nothing. -band'ing the values will reveal that 'Read' is fully contained as a subset of 'FullControl', so I corrected this as well. However this led me to (3) below...

3:  If the 'Requested' Rights are subsets of each other, the Test would also always fail. For example, assigning
@("Modify", "Write") to a folder with no permissions actually just results in @("Modify") in the resulting Enum, as "Write" is a fully contained subset of "Modify" and thus wont be returned individually in the stringified version of the enum. The fix for that was pre-converting the input "Rights" to the FileAccess enum and then diffing the enums directly. This was more or less already fixed by my original implementation of the 1 and 2 fixes, however required the special foreach loop handling in Ensure Absent to properly handle the absent case and preserve what I assume was the intended behavior before my changes.

I'm not sure what the old behavior was on multi-permission ensure absent before (given that multi-permission didn't work before I'd consider that behavior undefined), but the behavior now is that if ANY of the (pre-enum-string) Ensure Absent permissions are wholly contained within the existing permissions, it will return false. The Set continues to remove the full ACL as it did before, regardless of what subset of existing permissions were requested to be removed by the Ensure Absent Rights.
So for a few examples: 
Test @("FullControl") Absent returns TRUE for a folder with existing @("Read", "Write") permissions, as FullControl is not fully contained by Read, Write. 
Test @("Read") Absent returns FALSE for a folder with existing @("Modify") permissions, as Read is fully contained by "Modify".
Test @("Read","Write") Absent returns FALSE for a folder with existing @("Modify") permissions, as either one is fully contained by "Modify".
Test @("Read","FullControl") Absent returns FALSE for a folder with existing @("Modify") permissions, as Read is fully contained by "Modify". # Note this is the reason for the Foreach loop in the Absent switch. Pre-combining "Read, FullControl" into the enum value would just yield "FullControl", which would cause the Test to pass as FullControl is not fully contained by "Modify".
Test @("FullControl") Absent returns TRUE for a folder with existing @("Modify") permissions, as FullControl is NOT fully contained by "Modify", even though they share "Read", "Write", etc.

I also improved the logging output, as I felt in the dark about what it was doing or how it was handling and combining the flags. Hopefully this is to your liking.

- Fixes #20

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28)

### CODE REVIEW

**Comment by EklipZgit** [comment]
I'll work on the failed tests

**Comment by EklipZgit** [comment]
@johlju I'm looking at the tests and it looks like the behavior for:
existing ACL: Read
DSC resource: Ensure 'Absent' with no rights specified.

is to leave "Read" on the folder. Can you confirm this is expected? The documentation doesn't reference this case at all and I would expect all rights removed if I created a resource like that. My changes are implemented as such. I can alter my implementation, but that does not seem like intuitive nor expected behavior when I say "ensure an ACL for a user is absent", and the test passes and leaves the ACL behind.

**Comment by johlju** [comment]
Yes I agree, it sounds like all the permission should be removed if a principal (account) shall be absent.

**Comment by EklipZgit** [comment]
Alright, thanks. I'm finishing up the tests now

**Comment by EklipZgit** [comment]
@johlju this should be good to merge if you approve. What is the process on getting a new version released on the gallery? This bug is blocking us from safely configuring our lower environments without retriggering IIS AppPool recycles on every DSC run because the resource fails the Test every time with the permission combination we need to set. The Set then runs every time, triggering IIS to see folder configuration changed and recycles the AppDomain in the AppPool. Currently our workaround is to stop enforcing the permissions with DSC, but we'd like to get that back in for obvious reasons. Thanks!

**Review by johlju — CHANGES_REQUESTED** [review]
Awesome work on this! :smiley:  I haven't fully reviewed it yet, I don't have the time this weekend (family obligations), but one thing caught my eye that I commented on.
To get this released we need to convert it to the continuous delivery pipeline https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/. I could help with that so we can get this released. 

A question; are there any breaking changes in this one with any potential existing configurations out there? Just so we can change version accordingly if that is the case. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-:-LzQVRqhAcZ9U--_Fc-n:bvtag8k)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @EklipZgit)

___
*[DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1, line 85 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQ_RiS8ImSzWJLyWAL:-LzQ_RiS8ImSzWJLyWAM:b4kurqm) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1#L85)):*
> ```
>         # such as successful SETs, but TEST's that fail every time, so this
>         # -like *\ workaround makes behavior consistent.
> ```

It a there are permissions for both `DOMAIN\Users` and `BUILTIN\Users` would this return both if the user provides just `Users`? :thinking: If so, maybe we should add `BUILTIN` to the name if there are no `DOMAIN\` in the identity? :thinking: 
___
*[DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1, line 343 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQbuJ2C1umGNdtUBs_:-LzQbuJ2C1umGNdtUBsa:bq9kh6j) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1#L343)):*
> ```
> Write-Verbose -Message ( 'Returning {0} due to the above failures.' -f $result )
> ```

Can't $result be either $false or $true?  In that case the text might need to change depending on the value?
___
*[Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1, line 721 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQYbda-MCrp31VNQPz:-LzQYbda-MCrp31VNQQ-:b-ndwt0h) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1#L721)):*
> ```
> Describe "MSFT_xFileSystemAccessRule Functional unit tests" {
> ```

This looks like an integration tests (in the sense that the system is changed). I suggest moving these new tests to the integration tests file instead, or add another file under the Tests/Integration folder. The unit tests should be non-invasive tests (that mocks) so that a contributor can run them on a dev-machine without changing the environment.

**Comment by johlju** [comment]
@EklipZgit Please update the unreleased section of the change log in the README.md as well. https://github.com/dsccommunity/xSystemSecurity/blob/dev/README.md#unreleased
You have a lot of good information in the PR description that might suite in the change log. Also note any entries that introduces breaking changes by prefixing them with `BREAKING CHANGES:`.

**Comment by johlju** [comment]
@EklipZgit I have prepared the change to the new CI pipeline in PR #30 (to be able to release this module). Either I wait to merge that PR until this PR is through, or I merge the PR with new CI pipeline and you then rebase and resolve any conflicts in this PR. I'm leaning to waiting for this PR.

**Comment by EklipZgit** [comment]
Working on the stuff from the review. 

re: breaking changes, no there shouldn't be any breaking changes, unless people have Ensure: Absent, Rights: @(), Identity: someIdentity
in a scenario where someIdentity DOES currently have an explicit ACL on that path, which in 1.4.0.0 does nothing, and after my change would strip the existing ACL as the resource implies it should. This is the only existing scenario that I had to modify. I have covered this in the readme update. I'll try to get this done shortly so you can merge it first before the pipeline change, if that's the way you were leaning.

Thanks!

**Review by EklipZgit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1, line 85 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQ_RiS8ImSzWJLyWAL:-LzcESHY7ccbEM-ulaa6:b2qmvig) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1#L85)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         # such as successful SETs, but TEST's that fail every time, so this
>         # -like *\ workaround makes behavior consistent.
> ```

It a there are permissions for both `DOMAIN\Users` and `BUILTIN\Users` would this return both if the user provides just `Users`? :thinking: If so, maybe we should add `BUILTIN` to the name if there are no `DOMAIN\` in the identity? :thinking: 
</blockquote></details>

Good catch, I hadn't considered that this could catch domain users. Unfortunately there are more than just BUILTIN/ affected, ('NT AUTHORITY\NETWORK SERVICE', etc) which are not obvious to a user of this module and cause inconsistent test/set behavior when used. I was concerned that there were many that I didn't know about, but it looks like from https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems that I probably just care about handling
BUILTIN\ (bunch of stuff)
NT AUTHORITY\  (Network Service)
NT SERVICES\   (All Services)
so I will explicitly handle those and remove the blanket handling that could confuse with domain users inadvertently.
___
*[DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1, line 343 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQbuJ2C1umGNdtUBs_:-LzcKPUkDPqKfaMA03A4:bsjn8qg) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1#L343)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Verbose -Message ( 'Returning {0} due to the above failures.' -f $result )
> ```

Can't $result be either $false or $true?  In that case the text might need to change depending on the value?
</blockquote></details>

Good catch, corrected
___
*[Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1, line 721 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQYbda-MCrp31VNQPz:-LzcKTZ-9LX_dekdkm6j:b-1xoflj) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1#L721)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Describe "MSFT_xFileSystemAccessRule Functional unit tests" {
> ```

This looks like an integration tests (in the sense that the system is changed). I suggest moving these new tests to the integration tests file instead, or add another file under the Tests/Integration folder. The unit tests should be non-invasive tests (that mocks) so that a contributor can run them on a dev-machine without changing the environment.
</blockquote></details>

Moved them. I had some issues originally with putting them in Integration and thought the TestEnvironment setup was interfering with my tests. They seem to be working now from that location so I will put them there.

**Review by EklipZgit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1, line 85 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQ_RiS8ImSzWJLyWAL:-LzcNCoaBvajfp1PtVCj:b-896fix) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1#L85)):*
<details><summary><i>Previously, EklipZgit (Travis Drake) wrote…</i></summary><blockquote>

Good catch, I hadn't considered that this could catch domain users. Unfortunately there are more than just BUILTIN/ affected, ('NT AUTHORITY\NETWORK SERVICE', etc) which are not obvious to a user of this module and cause inconsistent test/set behavior when used. I was concerned that there were many that I didn't know about, but it looks like from https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems that I probably just care about handling
BUILTIN\ (bunch of stuff)
NT AUTHORITY\  (Network Service)
NT SERVICES\   (All Services)
so I will explicitly handle those and remove the blanket handling that could confuse with domain users inadvertently.

</blockquote></details>

Done.
___
*[DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1, line 343 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQbuJ2C1umGNdtUBs_:-LzcNEwHEqN0SND-9Kez:b-896fix) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/DSCResources/MSFT_xFileSystemAccessRule/MSFT_xFileSystemAccessRule.psm1#L343)):*
<details><summary><i>Previously, EklipZgit (Travis Drake) wrote…</i></summary><blockquote>

Good catch, corrected
</blockquote></details>

Done.
___
*[Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1, line 721 at r3](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-LzQYbda-MCrp31VNQPz:-LzcNGQg4NUJ0QqYYbJI:b-896fix) ([raw file](https://github.com/dsccommunity/xsystemsecurity/blob/166ce068e22773525d587d29cc482a469defa215/Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1#L721)):*
<details><summary><i>Previously, EklipZgit (Travis Drake) wrote…</i></summary><blockquote>

Moved them. I had some issues originally with putting them in Integration and thought the TestEnvironment setup was interfering with my tests. They seem to be working now from that location so I will put them there.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

Awesome work on this one!

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xsystemsecurity/28#-:-LzgyFmeEEwmm4Khi-kC:brynqql)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@EklipZgit I fixed up new CI and released a new version.

**Pull request merged**
