### PR TITLE
New xFileSystemAccessRule resource

### PR DESCRIPTION
**Pull request by BrianFarnhill**
A new resource that can be used to grant or remove permissions from a specific folder/file. 

Included is the resource, updated doco, as well as unit/integration tests.

Let me know if there are any issues.

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsystemsecurity/7)

### CODE REVIEW

**Comment by Indhukrishna** [comment]
_[Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1, line 89 [r2]](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7#-KOvxTnQaPKkEqWhlnN5:-KOvxTnQaPKkEqWhlnN6:b-hocz2z) ([raw file](https://github.com/powershell/xsystemsecurity/blob/f048a5a183ee16cb6415b8de2c8af0769c0912a5/Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1#L89)):_

> ``` PowerShell
>             Context "A permission exists and should, including correct rights" {
>                 $testParams = @{
>                     Path = "C:\TestFolder"
> ```

Can you please update the tests to use $env:SystemDrive instead of hard-coded drive letters?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7)_

**Comment by BrianFarnhill** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1, line 89 [r2]](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7#-KOvxTnQaPKkEqWhlnN5:-KPAF83XVedj7R0MIjwt:b-896fix) ([raw file](https://github.com/powershell/xsystemsecurity/blob/f048a5a183ee16cb6415b8de2c8af0769c0912a5/Tests/Unit/MSFT_xFileSystemAccessRule.tests.ps1#L89)):_
<details><summary>

<i>Previously, Indhukrishna (Indhu Sivaramakrishnan) wrote…</i></summary>



> Can you please update the tests to use $env:SystemDrive instead of hard-coded drive letters?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7)_

**Comment by Indhukrishna** [comment]
Reviewed 1 of 13 files at r1, 4 of 12 files at r2, 2 of 2 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1, line 22 [r3]](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7#-KPE7emqlKjoWNFvxLV2:-KPE7emqlKjoWNFvxLV3:bi5sqrp) ([raw file](https://github.com/powershell/xsystemsecurity/blob/a3577944c1ea7a4cd7f8a951f5bdc895951cf82b/Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1#L22)):_

> ``` PowerShell
>     . $ConfigFile
> 
>     New-Item -Path "C:\SampleFolder" -ItemType Directory
> ```

Can you also update this to use $env:systemdrive?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7)_

**Comment by Indhukrishna** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1, line 92 [r3]](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7#-KPE7nCWYx0CasWuNsEJ:-KPE7nCWYx0CasWuNsEK:bi5sqrp) ([raw file](https://github.com/powershell/xsystemsecurity/blob/a3577944c1ea7a4cd7f8a951f5bdc895951cf82b/Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1#L92)):_

> ``` PowerShell
> 
> 
>         Remove-Item -Path "C:\SampleFolder" -Recurse -Force -Confirm:$false
> ```

Can you also update this to use $env:systemdrive?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7)_

**Comment by BrianFarnhill** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1, line 22 [r3]](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7#-KPE7emqlKjoWNFvxLV2:-KPFRCpBFYbrKLebTg8L:b-896fix) ([raw file](https://github.com/powershell/xsystemsecurity/blob/a3577944c1ea7a4cd7f8a951f5bdc895951cf82b/Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1#L22)):_
<details><summary>

<i>Previously, Indhukrishna (Indhu Sivaramakrishnan) wrote…</i></summary>



> Can you also update this to use $env:systemdrive?
> </details>
> Done.

---

_[Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1, line 92 [r3]](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7#-KPE7nCWYx0CasWuNsEJ:-KPFRDjDI4TLhMU27Npx:b-896fix) ([raw file](https://github.com/powershell/xsystemsecurity/blob/a3577944c1ea7a4cd7f8a951f5bdc895951cf82b/Tests/Integration/MSFT_xFileSystemAccessRule.integration.tests.ps1#L92)):_
<details><summary>

<i>Previously, Indhukrishna (Indhu Sivaramakrishnan) wrote…</i></summary>



> Can you also update this to use $env:systemdrive?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7)_

**Comment by Indhukrishna** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsystemsecurity/7)_

**Pull request merged**
