### PR TITLE
Updated FileSystemACL Set

### PR DESCRIPTION
**Pull request by dchristian3188**
Modified the the way the ACL is built in the Set command. Please see:
https://github.com/PowerShell/xSystemSecurity/issues/11

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsystemsecurity/14)

### CODE REVIEW

**Comment by dchristian3188** [comment]
Sorry, i failed to update the pester test mock commands to work with the new method... Let me take a stab at fixing...

**Comment by duffney** [comment]
any ideas on what this change needs to get accepted? or when it will be accepted? Ran into this today and would like to keep using the resource instead of using xscript or cNTFS resources.

**Comment by johlju** [comment]
Seems the author did not yet updated the tests - and since that was 11 months ago I would say this PR is abandoned. 
If the original author do not have time to resolve this another contributor need to continue the work so it can be merged. In this case it looks like the unit test need to be written. 

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#how-to-continue-working-on-a-pull-request-when-an-author-contributor-is-unable-to-complete-it

**Comment by johlju** [comment]
Hmm. I was to quick there. Seems the unit tests  was resolved. 

@kwirkykat do you have time to review this PR?

**Review by kwirkykat — APPROVED** [review]

**Pull request merged**
